//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP_Algorithm.WFA.Languages {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP_Algorithm.WFA.Languages.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   en-GB benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnglishCodeGB_UK {
            get {
                return ResourceManager.GetString("EnglishCodeGB_UK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   en-US benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnglishCodeUS {
            get {
                return ResourceManager.GetString("EnglishCodeUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English (United Kingdom) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnglishUK {
            get {
                return ResourceManager.GetString("EnglishUK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   English (United States) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string EnglishUS {
            get {
                return ResourceManager.GetString("EnglishUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   tr-TR benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TurkishCodeTR {
            get {
                return ResourceManager.GetString("TurkishCodeTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Türkçe (Türkiye) benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string TurkishTR {
            get {
                return ResourceManager.GetString("TurkishTR", resourceCulture);
            }
        }
    }
}
