//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICP_Algorithm.WFA.Languages {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICP_Algorithm.WFA.Languages.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   &amp;About benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string About2 {
            get {
                return ResourceManager.GetString("About2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Angle benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Angle {
            get {
                return ResourceManager.GetString("Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   angle:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string angle2 {
            get {
                return ResourceManager.GetString("angle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A &amp;Tutorial on Rigid Registration benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string aTutorialOnRigidRegistration {
            get {
                return ResourceManager.GetString("aTutorialOnRigidRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   error:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   error=  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string error2 {
            get {
                return ResourceManager.GetString("error2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Exit benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;File benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ending ICP since for loop satisfied benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ForLoop {
            get {
                return ResourceManager.GetString("ForLoop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   General benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Github Web Page benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string githubWebPage {
            get {
                return ResourceManager.GetString("githubWebPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Initial parameters respect to Top Left benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string grpBoxInitialTopLeft {
            get {
                return ResourceManager.GetString("grpBoxInitialTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Transformation parameters respect to Top Left benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string grpBoxTransformationTopLeft {
            get {
                return ResourceManager.GetString("grpBoxTransformationTopLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Help benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ICP time =  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ICPtime {
            get {
                return ResourceManager.GetString("ICPtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   iteration=  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string iteration {
            get {
                return ResourceManager.GetString("iteration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language: benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ICP (Iterative Closest Point) Algorithm in C# benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ending ICP since min error satisfied benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string MinError {
            get {
                return ResourceManager.GetString("MinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ms benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ms {
            get {
                return ResourceManager.GetString("ms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Noisy Sample benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NoisySample {
            get {
                return ResourceManager.GetString("NoisySample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Normal Sample benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string NormalSample {
            get {
                return ResourceManager.GetString("NormalSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;OK benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Options benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Options benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string OptionsTitle {
            get {
                return ResourceManager.GetString("OptionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Report an issue benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ReportAnIssue {
            get {
                return ResourceManager.GetString("ReportAnIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Show Final benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string ShowFinal {
            get {
                return ResourceManager.GetString("ShowFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time= benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   time:  benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Time2 {
            get {
                return ResourceManager.GetString("Time2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &amp;Tools benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   X benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string X {
            get {
                return ResourceManager.GetString("X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Y benzeri yerelleştirilmiş bir dize arar.
        /// </summary>
        internal static string Y {
            get {
                return ResourceManager.GetString("Y", resourceCulture);
            }
        }
    }
}
